### ISSUE TITLE
case sensitivity handling on openstack

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#103]
If multiple security groups with the same name exist when launching an instance, openstack will raise the following exception:
```
Multiple security_group matches found for name 'cloudlaunch', use an ID to be more specific. (HTTP 409) (Request-ID: req-58cf4f64-0ee7-4a5f-b0d1-c7d285a1e0fe)
```
It looks like we need to make the firewalls.find() case insensitive, and possibly more widely for other resources too. Also, AWS behaviour is unknown.

**Comment by nuwang** [comment]
@afgane @almahmoud This if fixed now right?

**Comment by almahmoud** [comment]
Yes! The find method now uses our generic list then find not service specific find, which is not ideal for efficiency but helps avoid the problem where it was expecting to find a single result, although there is no uniqueness enforcement at creation time
