### ISSUE TITLE
Update Azure Storage package to v1.0 or newer

### ISSUE THREAD

**Issue by VJalili** [CloudVE/cloudbridge#122]
We're using `azure-storage`: 

https://github.com/gvlproject/cloudbridge/blob/6f4ad9d43e36cf0064789214269a0d479cfed63b/setup.py#L34

however, this package is no longer supported, and it is now broken-down to smaller and separate packages (e.g., `azure-storage-blob`, `azure-storage-file`, and `azure-storage-queue`).

> prior to and including version 0.36.0, there used to be a single package (azure-storage) containing all services. It is no longer supported, and users should install the 3 before-mentioned service packages individually, depending on the need [[ref](https://github.com/Azure/azure-storage-python#download)]

I recommend planning to make this transition (before `v1.0` release) as all newer features (and possibly bug fixes) all happen on the new versions.

**Comment by almahmoud** [comment]
Done in https://github.com/CloudVE/cloudbridge/commit/5e30f2e86c0ab33fd2fa652de9b31a4a4a6b688b
