### ISSUE TITLE
Support multiple signatures of `BlockBlobService`

### ISSUE THREAD

**Issue by VJalili** [CloudVE/cloudbridge#128]
The class `BlockBlobService` has multiple signatures, and some are available only in the newer versions of Azure libraries (e.g., v1.0 of `azure.storage.blob`). Therefore, IMHO it would be useful to support various signatures of the `BlockBlobService` class once the issue [#122](https://github.com/CloudVE/cloudbridge/issues/122) is resolved.

**Comment by afgane** [comment]
Done in #136.
