### ISSUE TITLE
new release possible ?

### ISSUE THREAD

**Issue by mvdbeek** [CloudVE/cloudbridge#133]
Any chance we could get a new release soon ?
cloudbridge 0.3.3 [requires boto <= 2.46.1](https://github.com/CloudVE/cloudbridge/blob/v0.3.3/setup.py#L25), while the current master branch doesn't use boto anymore.

This pin causes some dependency conflicts in galaxy, which uses cloudbridge in the cloud object store.

**Comment by afgane** [comment]
The new release is coming next week. We have been working on the release
tagged issues for a while now and @vjalili will do one remaining bit on
Monday before we can package the release.

**Comment by mvdbeek** [comment]
Cool, looking forward to this!

**Comment by nuwang** [comment]
@mvdbeek We've run into some new issues, so it's taking a little longer than expected. Since this is v1.0.0, we are trying to get the interface as stable as possible before the release.

**Comment by mvdbeek** [comment]
No worries, I should have mentioned that I worked around this, and ultimately it wasn't even cloudbridge that was brining in the dependency, that was actually the genomespace client, which we can and should provide via Conda. Good luck with the release!

**Comment by afgane** [comment]
Done. See https://github.com/CloudVE/cloudbridge/releases
