### ISSUE TITLE
Unicode vs ASCII discrepancy in config

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/cloudbridge#140]
In Python 2, `_get_config_value` function in `base/provider.py` returns an ASCII string when the configuration comes from a dict, and a unicode string when the configuration comes from file.

**Comment by nuwang** [comment]
Can we add a test for this? I think a simple is_unicode kind of test would be good.

**Comment by afgane** [comment]
Did env and config as well as types but not ini as that would require creating a file on the test server and that seems overstepping a bit.
