### ISSUE TITLE
AWS instance type list is incomplete

### ISSUE THREAD

**Issue by felix-wolfheimer** [CloudVE/cloudbridge#148]
Tried using the following code from the "getting started" page to query available instance types in AWS:

```
#!/usr/bin/env python3
import sys
from cloudbridge.cloud.factory import CloudProviderFactory, ProviderList

provider = CloudProviderFactory().create_provider(ProviderList.AWS, {})
for i in provider.compute.vm_types.list():
   sys.stdout.write('{}\n'.format(i))
```
This gives me the following list of instance types:
```
<CB-AWSVMType: m1.small>
<CB-AWSVMType: m1.medium>
<CB-AWSVMType: m1.large>
<CB-AWSVMType: m1.xlarge>
<CB-AWSVMType: m3.medium>
<CB-AWSVMType: m3.large>
<CB-AWSVMType: m3.xlarge>
<CB-AWSVMType: m3.2xlarge>
<CB-AWSVMType: c1.medium>
<CB-AWSVMType: c1.xlarge>
<CB-AWSVMType: cc2.8xlarge>
<CB-AWSVMType: c3.large>
<CB-AWSVMType: c3.xlarge>
<CB-AWSVMType: c3.2xlarge>
<CB-AWSVMType: c3.4xlarge>
<CB-AWSVMType: c3.8xlarge>
<CB-AWSVMType: g2.2xlarge>
<CB-AWSVMType: g2.8xlarge>
<CB-AWSVMType: m2.xlarge>
<CB-AWSVMType: m2.2xlarge>
<CB-AWSVMType: m2.4xlarge>
<CB-AWSVMType: cr1.8xlarge>
<CB-AWSVMType: r3.large>
<CB-AWSVMType: r3.xlarge>
<CB-AWSVMType: r3.2xlarge>
<CB-AWSVMType: r3.4xlarge>
<CB-AWSVMType: r3.8xlarge>
<CB-AWSVMType: i2.xlarge>
<CB-AWSVMType: i2.2xlarge>
<CB-AWSVMType: i2.4xlarge>
<CB-AWSVMType: i2.8xlarge>
<CB-AWSVMType: hs1.8xlarge>
<CB-AWSVMType: t1.micro>
<CB-AWSVMType: t3.nano>
<CB-AWSVMType: t3.micro>
<CB-AWSVMType: t3.small>
<CB-AWSVMType: t3.medium>
<CB-AWSVMType: t3.large>
<CB-AWSVMType: t3.xlarge>
<CB-AWSVMType: t3.2xlarge>
<CB-AWSVMType: t2.nano>
<CB-AWSVMType: t2.micro>
<CB-AWSVMType: t2.small>
<CB-AWSVMType: t2.medium>
<CB-AWSVMType: t2.large>
<CB-AWSVMType: t2.xlarge>
<CB-AWSVMType: t2.2xlarge>
<CB-AWSVMType: m5.large>
<CB-AWSVMType: m5.xlarge>
<CB-AWSVMType: m5.2xlarge>
```
This list seems incomplete as, e.g., GPU instance types (g3, p2, p3) are missing, also c4 instances are missing completely.

**Comment by nuwang** [comment]
This is probably because you've used the list() method, which pages in results by default. Instead, try the built in iteration capabilities:
```
for i in provider.compute.vm_types:
   sys.stdout.write('{}\n'.format(i))
```
See here for more info: https://cloudbridge.readthedocs.io/en/latest/topics/paging_and_iteration.html

Let us know whether that solves the issue.

**Comment by felix-wolfheimer** [comment]
Wow, indeed! That gives a complete list. Thanks for pointing me to this! 
Is it possible to get only the instance types supported in a certain region? In AWS especially the "high-end" instance types (like p3) are not available in all regions. I tried using the pricing API, which seems to be the only way to get this information currently (except for maintaining a static list myself), but this is far from optimal as querying the pricing API takes a bit of time and some instance types are missing in the results.
