### ISSUE TITLE
Authentication using IAM instance role (AWS) or MSI (Azure)

### ISSUE THREAD

**Issue by felix-wolfheimer** [CloudVE/cloudbridge#149]
Storing credentials in the code, in the environment, or in config files, which is somehow considered to be not best practice, can be prevented by using the IAM role (AWS) or the MSI (Azure) of the instance on which the script is running (if running on an instance of the provider which is contacted by cloudbridge). The code doesn't seem to allow this currently. Having the option to use this type of authentication when creating a provider object would be great.

**Comment by nuwang** [comment]
Thanks for this suggestion. If you're in a position to make a PR for this, that would be excellent. Perhaps @VJalili has some comments on this.

**Comment by nuwang** [comment]
@felix-wolfheimer There is an optional parameter to support this that has been added in: https://github.com/CloudVE/cloudbridge/pull/203
