### ISSUE TITLE
Example code errors

### ISSUE THREAD

**Issue by felix-wolfheimer** [CloudVE/cloudbridge#150]
The code on the example page has errors:

1. The key name is invalid (cloudbridge_intro). Using this name gives an exception:

```
cloudbridge.cloud.interfaces.exceptions.InvalidNameException: Invalid name: cloudbridge_intro. Name must be at least 3 characters long and at most 63 characters. It must consist of lowercase letters, numbers, or dashes. The name must not start or end with a dash.
```

2. The firewall creation throws an exception:
```
  File "./test.py", line 31, in create
    label='cloudbridge-intro', description='A VM firewall used by CloudBridge', network=net.id)
TypeError: create() got an unexpected keyword argument 'network'
```
Looking into the code, it should be "network_id" instead of "network".

3. Instance creation fails with an exception as well:
```
  File "./test.py", line 42, in create
    subnet=sn, key_pair=kp, vm_firewalls=[fw])
TypeError: create() missing 1 required positional argument: 'zone'
```
Seems that the example is not up to date with the code in the repo. Is there updated example code available?

**Comment by nuwang** [comment]
Thanks for reporting this. The documentation can be fixed, but it looks like in the second case, the example code is correct, but the interface is not! It actually ought to accept a network parameter, not a network_id parameter for the sake of consistency. I'm not really sure how we missed this, but it needs an urgent fix. ping @afgane @almahmoud

**Comment by nuwang** [comment]
@felix-wolfheimer I've just pushed out an update that fixes the doc errors. readthedocs should rebuild soon with the updated version. I'll file a new issue to track the network_id parameter.

**Comment by afgane** [comment]
@almahmoud how about opening a WIP PR for the docs? It would make it more visible and we all can pitch in.
