### ISSUE TITLE
Not picking up existing VM Firewall or routers during an instance launch

### ISSUE THREAD

**Issue by afgane** [CloudVE/cloudbridge#167]
We keep running into the following error at instance launch on CloudLaunch (on Jetstream at least):
```
FAILURE 
Create appliance task failed: More than one SecurityGroup exists with the name 'cloudlaunch-vm'.
```

**Comment by afgane** [comment]
Possibly related naming issue with routers and we have a bunch of them, all bearing the same name.
```
FAILURE 
Create appliance task failed: Quota exceeded for resources: ['router']. Neutron server returns request_ids: ['req-5233069c-299f-410c-b80a-48b9b64fb79e']
```

**Comment by almahmoud** [comment]
First issue fixed in https://github.com/CloudVE/cloudbridge/commit/5328b65db9162b29b5179aa4a61bce6122f88e9d and https://github.com/galaxyproject/cloudlaunch/pull/165
