### ISSUE TITLE
Azure firewall from_port and to_port are different

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#169]
azure firewall from_port and to_port are namedtuples, whereas it's a string for everything else. Also, the tests don't seem to catch the issue.

**Comment by almahmoud** [comment]
Tuple is used internally, but `from/to_port` properties return an `int` in all providers.
A change that came from looking at this is to GCE Firewall create method to conform to other providers (description optional, network mandatory): will be resolved with standardized public methods with event system.
