### ISSUE TITLE
Standardizing Google objects naming

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/cloudbridge#175]
Right now, we have classes prefixed GCP, GCE, and GCS, and some classes that are not named following our convention (e.g. GCSObject = GCEBucketObject)
After a conversation on Gitter, @afgane and I came to the conclusion that the easiest way to keep consistency and not have to change much down the stream is to rename everything to GCE. I removed the commit for now, as to avoid later merge conflicts between `master` and `middleware` branches among other things, but we should likely standardize GCE names before the new release.
Documenting the decision to move to GCE prefix here in case somebody has another suggestions, and to not forget to do the refactoring.

**Comment by nuwang** [comment]
Since it's a simple search replace, why not standardise on GCP? Seems more appropriate than GCE in the long run?

**Comment by afgane** [comment]
It didn't seem like that big of a deal whether it's GCE or GCP yet env variable names already exist referencing GCE and are used elsewhere (e.g., CloudLaunch) so the thinking was that changing less would require less changes and testing downstream (again, given that the diff between GCE and GCP didn't really seem that big of a deal).

**Comment by almahmoud** [comment]
I think conceptually GCP is better, but as Enis said, that would require more change.
What I could do is change it all to GCE first, make that standardizing commit, then attempt to change all GCE to GCP everywhere, including CloudLaunch & DJCloudBridge (anywhere else?), and see if there are any problems. If it works we can stick to GCP, if it proves to be more complicated, go back to GCE?

**Comment by nuwang** [comment]
Alex has fixed this in: https://github.com/CloudVE/cloudbridge/pull/189
