### ISSUE TITLE
Does cloudbridge intend to support  aws spot instance? or spot fleet request?

### ISSUE THREAD

**Issue by niejn** [CloudVE/cloudbridge#205]
Thanks for providing such an excellent lib, correct me if I am wrong, I noticed that there is no support for requesting spot instances in AWS, In boto3, I can useing client.request_spot_fleet(*args, **kwargs) and client.request_spot_instances(*args, **kwargs) to requset spot instances, Can I use cloudbridge to do that? Thank you!

**Comment by nuwang** [comment]
There's currently no direct abstraction for spot instances in cloudbridge,  but we'd welcome a PR for it. However,  if you want to simply call the above methods, you can do so via the cloudbridge provider which is only a thin wrapper around boto3.

'provider. session.client("ec2")' will give access to a boto3 client object through which you can call the above methods.

**Comment by niejn** [comment]
Thank you very much indeed!!! That really solves my problem.
