### ISSUE TITLE
Azure OS Provisioning for VM using image created from VM snapshot encountering OSProvisioningTimedOut

### ISSUE THREAD

**Issue by niejn** [CloudVE/cloudbridge#222]
when testing test_create_and_list_image, facing OSProvisioningTimedOut, however, the provisioning succeeded eventually.

**Comment by nuwang** [comment]
@niejn Can you paste the full stack trace? This exception looks like it's being raised by Azure, and not CloudBridge, so it may be an issue on their end?

**Comment by niejn** [comment]
![2019-09-26 14-43-03屏幕截图](https://user-images.githubusercontent.com/24802306/65667439-521c7100-e072-11e9-89bf-f5c082e183c3.png)

**Comment by niejn** [comment]
Thanks a lot, I found the similar issue in azure  Is there any way to increase timeout for provisioning a VM?https://github.com/Azure/azure-sdk-for-node/issues/1491. It seems to them, there is no way to increase the timeout, I am curious that whether you faced the same problem before, and how to solve it.

**Comment by nuwang** [comment]
I don't recall having faced this issue no. However, judging by the error message, could it be an image issue with the machine image you're using for the tests? Are you using the default image 'Canonical:UbuntuServer:16.04.0-LTS:latest' or using a custom image? Perhaps you could try using a different image by setting the CB_IMAGE_AZURE env var before running the tests? https://github.com/CloudVE/cloudbridge/blob/200e30940aac9001666fb73b505e4a77a6da621d/tests/helpers/__init__.py#L106

**Comment by nuwang** [comment]
Also, @almahmoud have you run into this?

**Comment by nuwang** [comment]
@niejn Is this looking good on your end? Can we close this issue?

**Comment by gm27rjpm** [comment]
Hi @nuwang 

Good Day!
I'm also facing the above similar error while provisioning a Linux (CentOS) VM using Packer from a custom built image in Azure.

Please advise if you have any suggestions on my below query.

How I built the custom image?
1. Created a Linux VM using CentOS7.7 Image chosen from Azure Marketplace.
2. Deprovision it using the below command.
    waagent -deprovision+user
3. Deallocated and Generalized it.
Link referred for step2 & 3: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image
4. Created a Image using that VM (Ex: Name - Centos-Custom-Image-v1)

I'm able to launch a new VM without any errors with that image from Azure Portal. 

Now, I tried to create a new image (Ex: New-Centos-Custom-Image-v1) by installing necessary packages, perform CIS benchmark standard practices in it by "Packer" on "Centos-Custom-Image-v1". 

I created it without any errors. While launching a new VM from that new custom image (built using packer), it is taking long time for deploying (25-30 min) before session timeout . And when I refresh the page after session timeout, it is showing the attached error message though the VM created successfully.

![image](https://user-images.githubusercontent.com/54054180/78972824-4c790b00-7b2c-11ea-8d87-de1477e3b12b.png)

I'm unable to create a VM backup in Azure with this errors. Could you please guide me to correct my errors if you have any idea?

It would be much helpful. Attached the packer build script also for your [reference.](### url)

[packer-image-build-azure.txt](https://github.com/MicrosoftDocs/azure-docs/files/4460200/packer-image-build-azure.txt)
![azure-vm-provision-error1](https://user-images.githubusercontent.com/54054180/78969268-2b142100-7b24-11ea-966c-9d86b4595e67.PNG)

Regards,
Guru Mohan

**Comment by nuwang** [comment]
@gm27rjpm This appears to be an issue on the Azure side of things. Have you checked the size of the resultant image? Perhaps it's very large? The best thing to do may be to contact Azure support and ask them for help on why this might be happening.

**Comment by gm27rjpm** [comment]
> @gm27rjpm This appears to be an issue on the Azure side of things. Have you checked the size of the resultant image? Perhaps it's very large? The best thing to do may be to contact Azure support and ask them for help on why this might be happening.

Thank you @nuwang!
I finally completed it using OpenLogic CentOS image available in Azure Market Place.
