### ISSUE TITLE
Way to get all instances of the availability zones

### ISSUE THREAD

**Issue by neelesh-a** [CloudVE/cloudbridge#246]
Currently when registered as AWS provider, and getting the list of instances, I get only the instances of one availability zone.

If I am interested in getting the list of all instances of a particular region in all its availability zone. How to get them?
Example:   I have 7 instances in ap-south-1a zone and 3 instances in ap-south-1b zone. Is there any way to retrieve all the 10 instances with a single provider, by providing the zones at configuration?

**Comment by nuwang** [comment]
@neelesh-a Thanks for reporting this. Each instance of a cloudbridge providers is tied to a specific zone. This was a conscious design decision and the reasons are documented [here](http://cloudbridge.cloudve.org/en/latest/topics/design_decisions.html#make-providers-single-zone). If you want to work across zones, the easiest way to do this is as follows:

```
(in pseudocode)

    provider = factory.createProvider(....)
    cloned_config = provider.config.copy()
    for zone for zone in provider.compute.regions.current.zones:
        new_config = cloned_config.update({'aws_zone_name': zone.name})
        new_provider = factory.createProvider(new_config)
   
```

**Comment by neelesh-a** [comment]
Thanks alot.
