### ISSUE TITLE
AWS IRSA support

### ISSUE THREAD

**Issue by innovate-invent** [CloudVE/cloudbridge#253]
Please add support for IRSA credentials in EKS. 

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration

Similarly GKE: https://cloud.google.com/blog/products/containers-kubernetes/introducing-workload-identity-better-authentication-for-your-gke-applications
and AKS: https://docs.microsoft.com/en-us/azure/aks/managed-aad

**Comment by nuwang** [comment]
@innovate-invent If you specify an empty dict when initializing the cloudbridge AWS provider, it defaults to IAM access. We use this in practice and it works as expected. While I haven't tested this for the other providers, it should work the same way. Is this what you're looking for or something else?

**Comment by innovate-invent** [comment]
Sorry, this issue is over a year old and I am not sure why I needed this. It is likely I was investigating a project that is dependant on cloudbridge. I am pretty sure I don't need this any more.
