### ISSUE TITLE
Network created on GCP via cloudbridge throws exceptions because of global region

### ISSUE THREAD

**Issue by selshowk** [CloudVE/cloudbridge#258]
I just tried running a variant of the "getting started" code on GCP and it failed.  Here is the snippet:
```
    net = provider.networking.networks.create(cidr_block='10.0.0.0/16',
                                              label=f'{network_name}-network')
    zone = provider.compute.regions.get(provider.region_name).zones[0]
    sn = net.subnets.create(
        cidr_block='10.0.0.0/28', label=f'{network_name}-subnet')
    #, zone=zone)
    router = provider.networking.routers.create(network=net,
            label=f'{network_name}-router')
    router.attach_subnet(sn)
```
Note that I've commented out the `zone` flag in the create subnet as this does not work (at least not with AWS) but I don't think this is the issue.

The network created above has no region but is global.  This effects the associated URL which breaks the `parse_url` function in the `network_id` property of routers and subnets.  In effect, once I've run the code above its no longer possible to work with the router or subnet objects (even to delete them) since they keep throwing exceptions.

Could you add support for `global` urls (see below) or guide me in doing so?  I found the relevant code/regex (in parse_url) but the overall logic would take me some time decode.

Here's a session output that should be useful:

```
In [36]: net
Out[36]: <CB-GCPNetwork: sheer-cloudbridge-network (https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/global/networks/sheer-cloudbridge-network-80ffee)>

In [37]: net.id
Out[37]: 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/global/networks/sheer-cloudbridge-network-80ffee'

In [38]: router.id
Out[38]: 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/regions/us-east1/routers/sheer-cloudbridge-router-ba056d'

In [39]: router.network_id
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-736814ce893c> in <module>
----> 1 router.network_id

/opt/conda/lib/python3.8/site-packages/cloudbridge/providers/gcp/resources.py in network_id(self)
   1465     def network_id(self):
   1466         parsed_url = self._provider.parse_url(self._router['network'])
-> 1467         network = parsed_url.get_resource()
   1468         return network['selfLink']
   1469 

AttributeError: 'NoneType' object has no attribute 'get_resource'

In [40]: router._router
Out[40]: 
{'id': '5814923775741871941',
 'creationTimestamp': '2020-11-24T04:16:42.680-08:00',
 'name': 'sheer-cloudbridge-router-ba056d',
 'region': 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/regions/us-east1',
 'network': 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/global/networks/sheer-cloudbridge-network-80ffee',
 'selfLink': 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/regions/us-east1/routers/sheer-cloudbridge-router-ba056d',
 'kind': 'compute#router'}

In [41]: router._provider
Out[41]: <cloudbridge.providers.gcp.provider.GCPCloudProvider at 0x7fa7b41e1340>

In [54]: router._provider.parse_url(router._router['network']) is None
Out[54]: True

```

**Comment by nuwang** [comment]
@selshowk Thanks for reporting this. It looks like the documentation needs to be fixed. We remove the zone parameter from `subnets.create()`, since each instance of a provider can only work in a specific zone. This simplified things quite a bit, but it looks like the documentation had been missed in that update.

GCP networks are global resources, whereas subnets are regional resources. (https://cloud.google.com/vpc/docs/vpc) So I guess that part is ok? It just looked like the `router.network_id` implementation has a bug. Either `self._router['network']` is null or `self._provider.parse_url(self._router['network'])` is not returning  a value. Would need to debug the function and see what's going on, and also add a test for this.

**Comment by selshowk** [comment]
Thanks for the info @nuwang .  The problem is that self._provider.parse_url is returning `None`.  As you can see in the session above `self._router["network"] = 'https://www.googleapis.com/compute/v1/projects/testvmcloudbridge/global/networks/sheer-cloudbridge-network-80ffee'`.  I suspect the problem is that the regex in the parse_url function is not working with the `global` in the URL but I haven't really checked this (but its the main thing that distinguishes this URL from others that don't have this problem).  

Note that I have the same problem with `subnet.network_id` but I expect a fix to the above will fix it as well.  Right now I can't delete either a router or a subnet once they've been created because the delete code uses the `network_id` property.

**Comment by nuwang** [comment]
@selshowk btw, are you using the master branch for this?

**Comment by selshowk** [comment]
No I'm using pypi though I'm reading through code from the master branch.  I can pull the master branch to test with but its easier (for my project) to use a pip package.

**Comment by nuwang** [comment]
We're hoping to release a new version this week or latest, mid next week, so can you test with the master branch and let us know whether things look ok?

**Comment by selshowk** [comment]
Sure, I'll try @nuwang .

**Comment by selshowk** [comment]
@nuwang this works with master branch so I think the issue can be closed.

**Comment by nuwang** [comment]
@selshowk The new version has just been released: https://github.com/CloudVE/cloudbridge/releases/tag/v2.1.0 so I'll close this now.
