### ISSUE TITLE
Update docs to mention that Azure default resource group is cloudbridge

### ISSUE THREAD

**Issue by FabioRosado** [CloudVE/cloudbridge#280]
This one caught me a bit off guard when I tested the new dev account. I followed the docs on [Create a provider](http://cloudbridge.cloudve.org/en/latest/getting_started.html#create-a-provider) and omitted `azure_resource_group` so cloudbridge was looking for the `cloudbridge` resource group, which was causing pretty much every test to fail.

If you would like, I'm happy to update this portion of the docs :smile:

**Comment by nuwang** [comment]
Aah, that's bad. Yes, please do. Perhaps we could also link to this section: http://cloudbridge.cloudve.org/en/latest/topics/setup.html
