### ISSUE TITLE
Should we allow users to specify read/write signed urls?

### ISSUE THREAD

**Issue by FabioRosado** [CloudVE/cloudbridge#293]
In GCP I had to create a custom method to generate a signed URL for a storage bucket because Cloudbridge is generating read only URLs. 

The aim of this issue, is to start a discussion if we should allow users to specify the type of permissions when generating the signed URL, we could add it as a parameter to be read (default) or write?

**Comment by nuwang** [comment]
That sounds good to me. It looks like almost all providers support either GET or POST as possible presigned url options.

**Comment by FabioRosado** [comment]
Great, I'll start hacking at it and open up a PR when I have a working code :smile:
