### ISSUE TITLE
Implement refresh() method for all resources and make securitygroup.name updatable.

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#70]
It seems logical to have a refresh method for most, if not all resources. For example, securitygroups do not have a refresh() method. Also, the security group's name property is not updatable.

**Comment by afgane** [comment]
Completed with object refresh in https://github.com/CloudVE/cloudbridge/commit/98959fc870379ccf7d415090c982cd23d8398f5e

**Comment by nuwang** [comment]
Name property is not updatable?

**Comment by almahmoud** [comment]
OS name setter in https://github.com/CloudVE/cloudbridge/commit/e88276a5e73f8ca9c35ed770d39cfc96f8d4fcf5

AWS security groups have a 'Group Name' which can't be changed. A name tag could be used if we want to make it updatable.
