### ISSUE TITLE
generate_temp_url for OpenStack and other providers

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#90]
Currently, only AWS has a generate_temp_url implementation. Both GCE and Azure have similar capabilities for generating temp_urls, so that should eventually come along.

OpenStack however, is somewhat different.
http://torgomatic.us/blog/2013/05/08/an-introduction-to-tempurl-in-openstack-swift/

Basically, to use temp_urls in OpenStack, you must first generate a secret key that is associated with your OpenStack account. Without this secret key, one cannot generate a temp url.

This however, means that each user must first associate a temp url with their account before they can start generating urls. Now, we could try to auto-generate this secret key, but the problem is that, you can only have one secret key associated with your account, so each time you associate a new secret key, all previous temp_urls for that account are invalidated. So if two different apps use two different keys, they risk cancelling each other out.

We could ask that users manually provide their secret key when initializing the provider, but that means that they must always provide that same secret key to every app that uses cloudbridge, something that is again rather unnatural. So the only portable implementation that comes to mind is:

1. Use a hash of the user's password as the secret key
2. CloudBridge will auto associate that hash with the user's account automatically each time you generate a temp_url.
3. If two different cloudbridge apps generate temp urls, it will work, because the hashes will be the same.
4. If a different application, associates its own secret with the account, all previous temp urls will be invalidated. But cloudbridge will re-associate a new hash, so it's ok for cloudbridge, but not so much for that other app.
5. We could also provide a facility to provide the secret key as a provider setting. If it's not provided, we can auto generate as above.

@afgane @VJalili Sound ok? Any security holes or problems that you can foresee with this approach?

**Comment by nuwang** [comment]
Looks like I've made a mistake. I forgot that a swift account corresponds to a project and not a user account. That invalidates that previous proposal and makes that issue far more difficult

**Comment by nuwang** [comment]
So this seems to have stemmed from a misunderstanding on my part. It turns out that the "secret key" can actually be retrieved at will.
http://chianingwang.blogspot.com/2015/09/how-to-generate-tempurl-for-swift.html

I guess this solves the problem. We can simply check for the existence of a secret key, and if it doesn't exist, generate a new one.

**Comment by VJalili** [comment]
I guess it would be better to not deal with secret (and/or access) key at cloudbridge level, so cloudbridge can rely on access and secret key provided to it by the user.
