### ISSUE TITLE
Instance needs the subnet property

### ISSUE THREAD

**Issue by afgane** [CloudVE/cloudbridge#92]
Instance objects do not have a property for which subnet they belong to (for info purposes or so other instances can be launched to match). While it's easy for the AWS and Azure side, OpenStack associates an instance w/ the network only?

**Comment by nuwang** [comment]
Good idea. For OpenStack, we'll need to infer the subnet from the port I guess - probably do the reverse of this:
https://github.com/gvlproject/cloudbridge/commit/f2241fb45e1afd849dfd63f6877edacff75a8518

However, if I recall correctly, it's possible for an instances to have multiple ports connected to different subnets. In that case, we can probably just return instance.nics[0].subnet?
